name: Test deepG setup

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v4

      - name: Install environment
        run: bash install.sh --cpu

      - name: Run tests
        run: |
          eval "$(~/miniforge3/bin/conda shell.bash hook)"
          mamba activate virusnet
          export RETICULATE_PYTHON=$(which python)
          Rscript tests/testthat.R
